Document: findbugs
Title: Debian findbugs Manual
Author: <insert document author here>
Abstract: This manual describes what findbugs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/findbugs/findbugs.sgml.gz

Format: postscript
Files: /usr/share/doc/findbugs/findbugs.ps.gz

Format: text
Files: /usr/share/doc/findbugs/findbugs.text.gz

Format: HTML
Index: /usr/share/doc/findbugs/html/index.html
Files: /usr/share/doc/findbugs/html/*.html
